package exceptions.dataexception.TyperEnumerations;

public enum FieldsEnum {
    EMAIL, PASSWORD, DATE, FC, NAME, USERNAME, INFO, CREDIT_NUMBER,CREDIT_MONTH,CREDIT_YEAR,
    EXERCISE_REST, EXERCISE_SETS, EXERCISE_REPS, EXERCISE,
    ROUTINE_NAME, ROUTINE_COMMENT
}
