module start {

    requires javafx.controls;
    requires javafx.fxml;
    requires org.jetbrains.annotations;
    requires java.sql;
    requires mysql.connector.j;
    requires java.desktop;
    exports viewone.popup.membershippopups;
    opens start to javafx.fxml;
    exports start;
    exports model.record;
    exports model;
    opens model;
    exports viewone.graphicalcontrollers.pt;
    exports viewone.graphicalcontrollers.launcher.gym;
    exports viewone;
    exports viewone.graphicalcontrollers.athlete;
    exports viewone.graphicalcontrollers.launcher;
    exports viewtwo.graphicalcontrollers.launcher;
    opens viewone to javafx.fxml;
    opens viewone.graphicalcontrollers.pt;
    exports  viewone.popup;
    opens viewone.popup to javafx.fxml;
    opens viewone.popup.membershippopups to javafx.fxml;
    opens viewone.graphicalcontrollers.launcher.gym to javafx.fxml;
    opens viewone.graphicalcontrollers.launcher to javafx.fxml;
    opens viewtwo.graphicalcontrollers.launcher to javafx.fxml;
    opens viewtwo.popups.controllers to javafx.fxml;
    exports viewone.graphicalcontrollers.gym;
    exports utils;
    exports beans;
    exports controllers;
    opens viewone.graphicalcontrollers.gym;
    opens viewone.graphicalcontrollers.athlete;
    exports engineering;
    opens engineering;
    exports viewone.managelistview;
    opens viewone.managelistview;
    exports viewone.managelistview.listcells;
    opens viewone.managelistview.listcells;
    opens utils;
    exports exceptions.dataexception;
    opens engineering.popups to javafx.fxml;
    exports exceptions.dataexception.typeenumerations;
    exports exceptions;
    exports viewone.beans;
    opens viewone.beans to javafx.fxml;
    opens beans to javafx.fxml;
    opens model.record;
    exports viewtwo.graphicalcontrollers.pt;
    opens viewtwo.graphicalcontrollers.pt;
exports model.cupons;
exports engineering.decorator;
    opens database.dao;
    exports database.dao;
    exports  exceptions.logger;
    opens viewtwo.popups to javafx.fxml;
    exports utils.listview;
    opens utils.listview;
        opens viewtwo.graphicalcontrollers.athlete;
    opens viewtwo.graphicalcontrollers.home;
}
